In [1]:
import pandas as pd
import os
import glob

In [20]:
def mergeAll(csvList, folder):
    stname = folder[:-1]
#     print "station name is", stname
    df1 = pd.read_csv(csvList[0])
    df1.rename(columns={'Values': csvList[0][:-4]}, inplace=True)
    df1 = df1.fillna('-1')
    df1[df1.columns[2]] = df1[df1.columns[2]].astype(str)
    df1['Time'] = df1["Date"].map(str) + ' ' + df1["Time"]
    df1 = df1.drop('Date',axis=1)
    df1 = df1.drop_duplicates(subset="Time")
    
#     print df1["Time"].value_counts()
    
#     print(df1.head)
#     print df1.shape
    for csv in csvList[1:]:
        print "Merging " + csv
        df2 = pd.read_csv(csv)
        if df2.shape[0] == 0:
            continue
        df2.rename(columns={'Values': csv[:-4]}, inplace=True)
        df2 = df2.fillna('-1')
        df2[df2.columns[2]] = df2[df2.columns[2]].astype(str)
        df2['Time'] = df2["Date"].map(str) + ' ' + df2["Time"]
        df2 = df2.drop('Date',axis=1)
        df2 = df2.drop_duplicates(subset="Time")
        print("df2 shape{0}".format(df2.shape))
        print df2.as_matrix()[0]
        valDf1 = df1[df1.columns[0]].as_matrix().tolist()
        valDf2 = df2[df2.columns[0]].as_matrix().tolist()
        
        valDf1.extend(valDf2)
        
        valDf1 = set(valDf1)
        valDf1 = list(valDf1)
        
        
        print len(valDf1)
#         print  valDf1[0]
        
        df1 = df1.merge(df2,how='outer')
        print df1.shape
    return df1
#     df1.to_csv(stName + ".csv")

In [22]:
print "Reading folders ..."
df = pd.DataFrame()

# df.m
# df.merge()
folders  = glob.glob("*/")
print folders
print
for f in folders:
    csvName = glob.glob(f+"*.csv")
    print "Creating " + f
    df = mergeAll(csvName, f)
    outPutFolder = "Combined Data/"
    print "Saving " + f
    df.to_csv(outPutFolder +  f[:-1]+'.csv',index=False)

Reading folders ...
['Anand Vihar/', 'IGI Airport/', 'ITO/', 'IHBAS/', 'MOBILE VAN/', 'Shadipur/', 'Mandir Marg/', 'Punjabi Bagh/', 'Civil Lines/', 'East Arjun Nagar-Delhi CPCB/', 'Sirifort/', 'R K Puram/', 'Combined Data/', 'Dwarka/', 'DTU/']

Creating Anand Vihar/
Merging Anand Vihar/Ambient Temperature(AT).csv
df2 shape(14524, 2)
['04/04/2015 10:00:00' '20.28']
19318
(19318, 3)
Merging Anand Vihar/Wind Direction(WD).csv
df2 shape(14553, 2)
['04/04/2015 10:00:00' '114.44']
19319
(19319, 4)
Merging Anand Vihar/Solar Radiation(SR).csv
df2 shape(14525, 2)
['04/04/2015 10:00:00' '435.11']
19319
(19319, 5)
Merging Anand Vihar/Ammonia(NH3).csv
df2 shape(18436, 2)
['24/03/2017 11:00:00' '452.0']
19322
(19322, 6)
Merging Anand Vihar/Oxides of Nitrogen(NOx).csv
df2 shape(18441, 2)
['24/03/2017 11:00:00' '373.90']
19322
(19322, 7)
Merging Anand Vihar/Relative Humidity(RH).csv
df2 shape(14553, 2)
['04/04/2015 10:00:00' '74.89']
19322
(19322, 8)
Merging Anand Vihar/P Xylene(PXY).csv
df2 shape(17398, 2)
['23/07/2012 13:00:00' '0.17']
19352
(19352, 9)
Merging Anand Vihar/Sulfur Dioxide(SO2).csv
df2 shape(17737, 2)
['23/03/2017 00:00:00' '23.45']
19353
(19353, 10)
Merging Anand Vihar/PM2.5(PM2.5).csv
df2 shape(14450, 2)
['23/03/2017 00:00:00' '132.45']
19354
(19354, 11)
Merging Anand Vihar/Toluene(TOL).csv
df2 shape(18823, 2)
['23/07/2012 13:00:00' '9.1']
19354
(19354, 12)
Merging Anand Vihar/Temperature(temp).csv
df2 shape(5609, 2)
['24/07/2012 22:00:00' '27.9']
19391
(19391, 13)
Merging Anand Vihar/Nitric Oxide(NO).csv
df2 shape(16659, 2)
['23/07/2012 13:00:00' '28.27']
19391
(19391, 14)
Merging Anand Vihar/Benzene(BEN).csv
df2 shape(15039, 2)
['23/07/2012 13:00:00' '1.41']
19391
(19391, 15)
Merging Anand Vihar/Ozone(O3).csv
df2 shape(16162, 2)
['23/07/2012 13:00:00' '63.07']
19391
(19391, 16)
Merging Anand Vihar/PM10(PM10).csv
df2 shape(14181, 2)
['23/03/2017 00:00:00' '398.00']
19391
(19391, 17)
Merging Anand Vihar/Bar Pressure(BP).csv
df2 shape(14523, 2)
['04/04/2015 10:00:00' '740.0']
19391
(19391, 18)
Merging Anand Vihar/Wind Speed(WS).csv
df2 shape(14553, 2)
['23/03/2017 00:00:00' '0.31']
19391
(19391, 19)
Saving Anand Vihar/
Creating IGI Airport/
Merging IGI Airport/Solar Radiation(SR).csv
Merging IGI Airport/PM10(RPM).csv
df2 shape(25599, 2)
['14/01/2011 00:00:00' '319.8']
38845
(38845, 3)
Merging IGI Airport/Ozone(OZONE).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '44.57']
38845
(38845, 4)
Merging IGI Airport/Wind Speed(Wind Speed S).csv
df2 shape(28399, 2)
['01/01/2011 00:00:00' '1.10']
38846
(38846, 5)
Merging IGI Airport/Ammonia(NH3).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '0.61']
38846
(38846, 6)
Merging IGI Airport/Oxides of Nitrogen(NOx).csv
Merging IGI Airport/Relative Humidity(RH).csv
df2 shape(31072, 2)
['01/01/2011 00:00:00' '100.00']
38846
(38846, 7)
Merging IGI Airport/Carbon Monoxide(CO).csv
df2 shape(38495, 2)
['01/01/2011 00:00:00' '-1']
38846
(38846, 8)
Merging IGI Airport/Toluene(Toluene).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '44.17']
38846
(38846, 9)
Merging IGI Airport/Sulfur Dioxide(SO2).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '8.22']
38846
(38846, 10)
Merging IGI Airport/Temperature(Temp).csv
df2 shape(33201, 2)
['01/01/2011 00:00:00' '11.49']
38846
(38846, 11)
Merging IGI Airport/Nitric Oxide(NO).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '40.72']
38846
(38846, 12)
Merging IGI Airport/PM2.5(Dust (PM2.5)).csv
df2 shape(33202, 2)
['01/01/2011 00:00:00' '-1']
38846
(38846, 13)
Merging IGI Airport/Benzene(Benzene).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '13.79']
38846
(38846, 14)
Merging IGI Airport/Wind Direction (Wind Dir S).csv
df2 shape(33202, 2)
['01/01/2011 00:00:00' '224.88']
38846
(38846, 15)
Merging IGI Airport/Vertical Wind Speed(VWS).csv
Merging IGI Airport/Xylene(M_P_Xylene).csv
df2 shape(38823, 2)
['01/01/2011 00:00:00' '-1.74']
38846
(38846, 16)
Merging IGI Airport/Bar Pressure(Bar Pressure).csv
df2 shape(33202, 2)
['01/01/2011 00:00:00' '987.53']
38846
(38846, 17)
Saving IGI Airport/
Creating ITO/
Merging ITO/Ozone(OZONE).csv
df2 shape(28781, 2)
['01/01/2011 00:00:00' '7.5']
33230
(33230, 3)
Merging ITO/Ammonia(NH3).csv
df2 shape(14214, 2)
['16/11/2013 15:00:00' '132.5']
33277
(33277, 4)
Merging ITO/Non Methane Hydro Carbon(NMHC).csv
Merging ITO/M & P Xylene(M_P_Xylene).csv
Merging ITO/Oxides of Nitrogen(NOx).csv
df2 shape(30913, 2)
['01/01/2011 00:00:00' '58.25']
33309
(33309, 5)
Merging ITO/Relative Humidity(RH).csv
Merging ITO/Carbon Monoxide(CO).csv
df2 shape(25701, 2)
['01/01/2011 00:00:00' '1.32']
33360
(33360, 6)
Merging ITO/Toluene(Toluene).csv
Merging ITO/Sulfur Dioxide(SO2).csv
df2 shape(28295, 2)
['01/01/2011 00:00:00' '6.25']
33435
(33435, 7)
Merging ITO/Temperature(Temp).csv
Merging ITO/PM2.5(PM2.5).csv
df2 shape(3105, 2)
['03/11/2016 11:00:00' '63.67']
33475
(33475, 8)
Merging ITO/Vertical Wind Speed(Wind Speed V).csv
Merging ITO/Nitric Oxide(NO).csv
df2 shape(31302, 2)
['01/01/2011 00:00:00' '52.27']
33535
(33535, 9)
Merging ITO/Wind Direction(Wind Dir S).csv
Merging ITO/PM10(PM10).csv
df2 shape(3119, 2)
['03/11/2016 11:00:00' '123.75']
33535
(33535, 10)
Merging ITO/Ethyl Benzene(Ethylben).csv
Merging ITO/Wind Speed (Wind Speed S).csv
Merging ITO/Solar Radiation(Solar Rad).csv
Merging ITO/Total Hydrocarbon(THC).csv
Merging ITO/O Xylene(O_Xylene).csv
Saving ITO/
Creating IHBAS/
Merging IHBAS/Nitrogen Dioxide(NO2).csv
df2 shape(34015, 2)
['01/01/2011 00:00:00' '18.08']
39036
(39036, 3)
Merging IHBAS/Ambient Temperature(AT).csv
df2 shape(8301, 2)
['09/11/2015 13:00:00' '29.67']
39085
(39085, 4)
Merging IHBAS/Wind Direction(WD).csv
df2 shape(8299, 2)
['09/11/2015 13:00:00' '264.89']
39133
(39133, 5)
Merging IHBAS/Solar Radiation(SR).csv
df2 shape(8258, 2)
['09/11/2015 13:00:00' '146.92']
39138
(39138, 6)
Merging IHBAS/Ozone(OZONE).csv
Merging IHBAS/Ammonia(NH3).csv
df2 shape(35561, 2)
['01/01/2011 00:00:00' '12.02']
39431
(39431, 7)
Merging IHBAS/Non Methane Hydro Carbon(NMHC).csv
df2 shape(38335, 2)
['01/01/2011 00:00:00' '923.65']
42896
(42896, 8)
Merging IHBAS/M & P Xylene(M_P_Xylene).csv
Merging IHBAS/Oxides of Nitrogen(NOx).csv
df2 shape(36841, 2)
['01/01/2011 00:00:00' '12.11']
42973
(42973, 9)
Merging IHBAS/Relative Humidity(RH).csv
df2 shape(43337, 2)
['01/01/2011 00:00:00' '87.23']
43960
(43960, 10)
Merging IHBAS/Carbon Monoxide(CO).csv
df2 shape(41823, 2)
['01/01/2011 00:00:00' '0.64']
44008
(44008, 11)
Merging IHBAS/Toluene(Toluene).csv
Merging IHBAS/Sulfur Dioxide(SO2).csv
df2 shape(39174, 2)
['01/01/2011 00:00:00' '3.45']
44035
(44035, 12)
Merging IHBAS/PM10(RSPM).csv
df2 shape(31115, 2)
['01/01/2011 00:00:00' '55.05']
44035
(44035, 13)
Merging IHBAS/Temperature(Temp).csv
df2 shape(35128, 2)
['01/01/2011 00:00:00' '10.3']
44035
(44035, 14)
Merging IHBAS/Methane(CH4).csv
df2 shape(37425, 2)
['01/01/2011 00:00:00' '2,884.09']
44060
(44060, 15)
Merging IHBAS/Nitric Oxide(NO).csv
df2 shape(39283, 2)
['01/01/2011 00:00:00' '2.3']
44340
(44340, 16)
Merging IHBAS/Bar Pressure(BP).csv
df2 shape(8238, 2)
['09/11/2015 13:00:00' '752.96']
44341
(44341, 17)
Merging IHBAS/Ethyl Benzene(Ethylben).csv
Merging IHBAS/Benzene(Benzene).csv
Merging IHBAS/Vertical Wind Speed(VWS).csv
df2 shape(7543, 2)
['11/11/2015 03:00:00' '-0.01']
44389
(44389, 18)
Merging IHBAS/Total Hydrocarbon(THC).csv
df2 shape(38000, 2)
['01/01/2011 00:00:00' '3,807.74']
44454
(44454, 19)
Merging IHBAS/O Xylene(O_Xylene).csv
Merging IHBAS/PM 2.5(PM2.5).csv
df2 shape(35149, 2)
['01/01/2012 12:00:00' '218.24']
44777
(44777, 20)
Saving IHBAS/
Creating MOBILE VAN/
Merging MOBILE VAN/Ozone(OZONE).csv
Merging MOBILE VAN/Suspended Particulate Matter.csv
Merging MOBILE VAN/Ammonia(NH3).csv
Merging MOBILE VAN/Non Methane Hydro Carbon(NMHC).csv
Merging MOBILE VAN/M & P Xylene(M_P_Xylene).csv
Merging MOBILE VAN/Oxides of Nitrogen(NOx).csv
df2 shape(3806, 2)
['01/01/2011 00:00:00' '24.25']
3807
(3807, 3)
Merging MOBILE VAN/Relative Humidity(RH).csv
Merging MOBILE VAN/Carbon Monoxide(CO).csv
df2 shape(4503, 2)
['01/01/2011 00:00:00' '-1']
4690
(4690, 4)
Merging MOBILE VAN/Toluene(Toluene).csv
Merging MOBILE VAN/Sulfur Dioxide(SO2).csv
df2 shape(4585, 2)
['01/01/2011 00:00:00' '5.75']
4924
(4924, 5)
Merging MOBILE VAN/PM10(RSPM).csv
Merging MOBILE VAN/Temperature(Temp).csv
Merging MOBILE VAN/Methane(CH4).csv
Merging MOBILE VAN/PM10(DUST).csv
df2 shape(5028, 2)
['01/01/2011 00:00:00' '-1']
5028
(5028, 6)
Merging MOBILE VAN/Vertical Wind Speed(Wind Speed V).csv
Merging MOBILE VAN/Nitric Oxide(NO).csv
df2 shape(3763, 2)
['01/01/2011 00:00:00' '4.0']
5028
(5028, 7)
Merging MOBILE VAN/Wind Direction(Wind Dir S).csv
Merging MOBILE VAN/PM2.5(Dust (PM2.5)).csv
Merging MOBILE VAN/Ethyl Benzene(Ethylben).csv
Merging MOBILE VAN/Wind Speed (Wind Speed S).csv
Merging MOBILE VAN/Benzene(Benzene).csv
Merging MOBILE VAN/Solar Radiation(Solar Rad).csv
Merging MOBILE VAN/Total Hydrocarbon(THC).csv
Merging MOBILE VAN/Bar Pressure(Bar Pressure).csv
Merging MOBILE VAN/O Xylene(O_Xylene).csv
Saving MOBILE VAN/
Creating Shadipur/
Merging Shadipur/Wind Speed (WS).csv
df2 shape(5941, 2)
['24/05/2016 14:00:00' '1.32']
40575
(40575, 3)
Merging Shadipur/Eth-Benzene(Eth-Benzene).csv
df2 shape(3333, 2)
['10/10/2016 14:00:00' '0.06']
40575
(40575, 4)
Merging Shadipur/Nitrogen Dioxide(NO2).csv
df2 shape(45677, 2)
['01/01/2011 00:00:00' '35.33']
49138
(49138, 5)
Merging Shadipur/Wind Direction(WD).csv
df2 shape(5926, 2)
['25/05/2016 09:00:00' '186.69']
49138
(49138, 6)
Merging Shadipur/Solar Radiation(SR).csv
df2 shape(5939, 2)
['24/05/2016 14:00:00' '778.21']
49138
(49138, 7)
Merging Shadipur/Ammonia(NH3).csv
Merging Shadipur/Non Methane Hydro Carbon(NMHC).csv
Merging Shadipur/Relative Humidity(RH).csv
df2 shape(50080, 2)
['01/01/2011 00:00:00' '86.8']
50512
(50512, 8)
Merging Shadipur/Carbon Monoxide(CO).csv
df2 shape(44351, 2)
['01/01/2011 00:00:00' '0.99']
50513
(50513, 9)
Merging Shadipur/Toluene(Toluene).csv
df2 shape(39599, 2)
['07/01/2011 09:00:00' '8.72']
50513
(50513, 10)
Merging Shadipur/Sulfur Dioxide(SO2).csv
df2 shape(45121, 2)
['01/01/2011 00:00:00' '5.53']
50514
(50514, 11)
Merging Shadipur/Temperature(TEMP).csv
df2 shape(50173, 2)
['01/01/2011 00:00:00' '9.18']
50514
(50514, 12)
Merging Shadipur/Methane(CH4).csv
Merging Shadipur/Ozone(Ozone).csv
df2 shape(46846, 2)
['01/01/2011 00:00:00' '190.23']
50515
(50515, 13)
Merging Shadipur/NOx(NOx).csv
df2 shape(45688, 2)
['01/01/2011 00:00:00' '26.42']
50515
(50515, 14)
Merging Shadipur/Nitric Oxide(NO).csv
df2 shape(43512, 2)
['01/01/2011 00:00:00' '12.31']
50515
(50515, 15)
Merging Shadipur/PM10(PM10).csv
Merging Shadipur/Bar Pressure(BP).csv
df2 shape(3429, 2)
['10/10/2016 12:00:00' '754.28']
50515
(50515, 16)
Merging Shadipur/Benzene(Benzene).csv
df2 shape(39672, 2)
['02/01/2011 01:00:00' '3.0']
50515
(50515, 17)
Merging Shadipur/Vertical Wind Speed(VWS).csv
df2 shape(5934, 2)
['24/05/2016 15:00:00' '1.59']
50515
(50515, 18)
Merging Shadipur/MP Xylene(MP Xylene).csv
df2 shape(38883, 2)
['03/01/2011 03:00:00' '0.28']
50515
(50515, 19)
Merging Shadipur/Total Hydrocarbon(THC).csv
Merging Shadipur/PM 2.5(PM2.5).csv
df2 shape(15288, 2)
['23/03/2015 17:00:00' '50.20']
50515
(50515, 20)
Saving Shadipur/
Creating Mandir Marg/
Merging Mandir Marg/Nitrogen Dioxide(NO2).csv
df2 shape(22783, 2)
['19/04/2011 13:00:00' '24.74']
23419
(23419, 3)
Merging Mandir Marg/Ambient Temperature(AT).csv
df2 shape(13369, 2)
['09/04/2015 14:00:00' '30.8']
23419
(23419, 4)
Merging Mandir Marg/Wind Direction(WD).csv
df2 shape(23406, 2)
['19/04/2011 13:00:00' '255.2']
23419
(23419, 5)
Merging Mandir Marg/Solar Radiation(SR).csv
df2 shape(13369, 2)
['09/04/2015 14:00:00' '376.0']
23419
(23419, 6)
Merging Mandir Marg/Ammonia(NH3).csv
df2 shape(22557, 2)
['19/04/2011 13:00:00' '32.04']
23419
(23419, 7)
Merging Mandir Marg/Non Methane Hydro Carbon(NMHC).csv
Merging Mandir Marg/M & P Xylene(M_P_Xylene).csv
df2 shape(10497, 2)
['19/04/2011 13:00:00' '-1']
23419
(23419, 8)
Merging Mandir Marg/Oxides of Nitrogen(NOx).csv
df2 shape(22814, 2)
['19/04/2011 13:00:00' '27.30']
23419
(23419, 9)
Merging Mandir Marg/Relative Humidity(RH).csv
df2 shape(23406, 2)
['19/04/2011 13:00:00' '16.2']
23419
(23419, 10)
Merging Mandir Marg/Carbon Monoxide(CO).csv
df2 shape(22691, 2)
['19/04/2011 13:00:00' '-1']
23421
(23421, 11)
Merging Mandir Marg/Sulfur Dioxide(SO2).csv
df2 shape(22686, 2)
['19/04/2011 13:00:00' '10.9']
23421
(23421, 12)
Merging Mandir Marg/Temperature(Temp).csv
df2 shape(10524, 2)
['19/04/2011 13:00:00' '37.0']
23421
(23421, 13)
Merging Mandir Marg/PM2.5(PM2.5).csv
df2 shape(13230, 2)
['09/04/2015 15:00:00' '38.0']
23421
(23421, 14)
Merging Mandir Marg/Toluene(TOL).csv
df2 shape(13322, 2)
['09/04/2015 15:00:00' '-1']
23421
(23421, 15)
Merging Mandir Marg/Methane(CH4).csv
Merging Mandir Marg/Ozone(Ozone).csv
df2 shape(10457, 2)
['19/04/2011 13:00:00' '228.58']
23421
(23421, 16)
Merging Mandir Marg/Vertical Wind Speed(Wind Speed V).csv
df2 shape(4899, 2)
['19/04/2011 13:00:00' '0.1']
23421
(23421, 17)
Merging Mandir Marg/Nitric Oxide(NO).csv
df2 shape(22770, 2)
['19/04/2011 13:00:00' '2.52']
23421
(23421, 18)
Merging Mandir Marg/Benzene(BEN).csv
df2 shape(13321, 2)
['09/04/2015 15:00:00' '-1']
23421
(23421, 19)
Merging Mandir Marg/PM10(PM10).csv
df2 shape(13038, 2)
['09/04/2015 15:00:00' '61.0']
23421
(23421, 20)
Merging Mandir Marg/Bar Pressure(BP).csv
df2 shape(13369, 2)
['09/04/2015 14:00:00' '735.0']
23421
(23421, 21)
Merging Mandir Marg/Ethyl Benzene(Ethylben).csv
Merging Mandir Marg/Total Hydrocarbon(THC).csv
Merging Mandir Marg/O Xylene(O_Xylene).csv
Saving Mandir Marg/
Creating Punjabi Bagh/
Merging Punjabi Bagh/Wind Direction(WD).csv
df2 shape(25663, 2)
['19/04/2011 13:00:00' '263.2']
25778
(25778, 3)
Merging Punjabi Bagh/Solar Radiation(SR).csv
df2 shape(15066, 2)
['07/04/2015 16:00:00' '94.0']
25778
(25778, 4)
Merging Punjabi Bagh/Suspended Particulate Matter.csv
Merging Punjabi Bagh/Ammonia(NH3).csv
df2 shape(24573, 2)
['19/04/2011 13:00:00' '23.58']
25778
(25778, 5)
Merging Punjabi Bagh/Non Methane Hydro Carbon(NMHC).csv
Merging Punjabi Bagh/Temperature(AT).csv
df2 shape(14654, 2)
['07/04/2015 16:00:00' '26.29']
25778
(25778, 6)
Merging Punjabi Bagh/Oxides of Nitrogen(NOx).csv
df2 shape(24706, 2)
['19/04/2011 13:00:00' '20.72']
25778
(25778, 7)
Merging Punjabi Bagh/Relative Humidity(RH).csv
df2 shape(25261, 2)
['19/04/2011 13:00:00' '36.4']
25778
(25778, 8)
Merging Punjabi Bagh/Carbon Monoxide(CO).csv
df2 shape(24824, 2)
['19/04/2011 13:00:00' '1.42']
25783
(25783, 9)
Merging Punjabi Bagh/P Xylene(PXY).csv
df2 shape(14936, 2)
['07/04/2015 16:00:00' '2.72']
25783
(25783, 10)
Merging Punjabi Bagh/Sulfur Dioxide(SO2).csv
df2 shape(24035, 2)
['24/04/2011 14:00:00' '17.9']
25783
(25783, 11)
Merging Punjabi Bagh/PM2.5(PM2.5).csv
df2 shape(14765, 2)
['07/04/2015 16:00:00' '55.0']
25799
(25799, 12)
Merging Punjabi Bagh/Methane(CH4).csv
Merging Punjabi Bagh/Toluene(Tol).csv
df2 shape(15012, 2)
['07/04/2015 16:00:00' '8.18']
25799
(25799, 13)
Merging Punjabi Bagh/Nitric Oxide(NO).csv
df2 shape(24688, 2)
['19/04/2011 13:00:00' '3.52']
25799
(25799, 14)
Merging Punjabi Bagh/Benzene(Ben).csv
df2 shape(14956, 2)
['07/04/2015 16:00:00' '1.56']
25799
(25799, 15)
Merging Punjabi Bagh/Ozone(O3).csv
df2 shape(14591, 2)
['07/04/2015 16:00:00' '109.92']
25800
(25800, 16)
Merging Punjabi Bagh/PM10(PM10).csv
df2 shape(14787, 2)
['07/04/2015 16:00:00' '151.67']
25801
(25801, 17)
Merging Punjabi Bagh/Bar Pressure(BP).csv
df2 shape(14963, 2)
['07/04/2015 16:00:00' '553.5']
25801
(25801, 18)
Merging Punjabi Bagh/Ethyl Benzene(Ethylben).csv
Merging Punjabi Bagh/Wind Speed(WS).csv
df2 shape(25663, 2)
['19/04/2011 13:00:00' '2.58']
25801
(25801, 19)
Merging Punjabi Bagh/Vertical Wind Speed(VWS).csv
df2 shape(9753, 2)
['07/04/2015 16:00:00' '-0.1']
25801
(25801, 20)
Merging Punjabi Bagh/Total Hydrocarbon(THC).csv
Merging Punjabi Bagh/O Xylene(O_Xylene).csv
Saving Punjabi Bagh/
Creating Civil Lines/
Merging Civil Lines/Solar Radiation(SR).csv
Merging Civil Lines/PM10(RPM).csv
df2 shape(26043, 2)
['01/01/2011 00:00:00' '520.25']
38883
(38883, 3)
Merging Civil Lines/Oxides of Nitrogen(NOx).csv
Merging Civil Lines/WindDirection(Wind Dir S).csv
df2 shape(36170, 2)
['01/01/2011 00:00:00' '217.85']
38893
(38893, 4)
Merging Civil Lines/Relative Humidity(RH).csv
df2 shape(21560, 2)
['01/01/2011 00:00:00' '88.30']
38893
(38893, 5)
Merging Civil Lines/Carbon Monoxide(CO).csv
df2 shape(34298, 2)
['01/01/2011 00:00:00' '6.68']
38895
(38895, 6)
Merging Civil Lines/Toluene(Toluene).csv
df2 shape(38869, 2)
['01/01/2011 00:00:00' '132.81']
38895
(38895, 7)
Merging Civil Lines/Sulfur Dioxide(SO2).csv
df2 shape(38869, 2)
['01/01/2011 00:00:00' '17.14']
38895
(38895, 8)
Merging Civil Lines/Rack Temperature(RT).csv
Merging Civil Lines/Rainfall(RF).csv
Merging Civil Lines/Xylene(PXY).csv
Merging Civil Lines/Nitric Oxide(NO).csv
df2 shape(38869, 2)
['01/01/2011 00:00:00' '71.92']
38895
(38895, 9)
Merging Civil Lines/Temperature(TMP).csv
Merging Civil Lines/OZONE(OZONE).csv
df2 shape(38869, 2)
['01/01/2011 00:00:00' '47.48']
38895
(38895, 10)
Merging Civil Lines/Benzene(Benzene).csv
df2 shape(36733, 2)
['01/01/2011 00:00:00' '18.45']
38895
(38895, 11)
Merging Civil Lines/Vertical Wind Speed(VWS).csv
Merging Civil Lines/Wind Speed S(WS).csv
Merging Civil Lines/Bar Pressure(Bar Pressure).csv
df2 shape(31828, 2)
['01/01/2011 00:00:00' '989.47']
38895
(38895, 12)
Merging Civil Lines/PM2.5(Dust (PM2.5) ).csv
df2 shape(30977, 2)
['04/05/2011 12:00:00' '150.97']
38895
(38895, 13)
Saving Civil Lines/
Creating East Arjun Nagar-Delhi CPCB/
Merging East Arjun Nagar-Delhi CPCB/Toluene(TOLUENE).csv
df2 shape(6116, 2)
['05/04/2016 12:00:00' '20.77']
6116
(6116, 3)
Merging East Arjun Nagar-Delhi CPCB/Benzene(BENZENE).csv
df2 shape(6114, 2)
['05/04/2016 14:00:00' '6.95']
6116
(6116, 4)
Merging East Arjun Nagar-Delhi CPCB/Mercury(Hg).csv
df2 shape(6116, 2)
['23/03/2017 00:00:00' '2.56']
6116
(6116, 5)
Merging East Arjun Nagar-Delhi CPCB/SO2(SO2).csv
df2 shape(6109, 2)
['23/03/2017 00:00:00' '20.12']
6116
(6116, 6)
Merging East Arjun Nagar-Delhi CPCB/Nitric Oxide(NO).csv
df2 shape(6117, 2)
['05/04/2016 12:00:00' '10.13']
6117
(6117, 7)
Merging East Arjun Nagar-Delhi CPCB/Ozone(O3).csv
df2 shape(6116, 2)
['23/03/2017 00:00:00' '27.05']
6117
(6117, 8)
Merging East Arjun Nagar-Delhi CPCB/Xylene(pXy).csv
df2 shape(5623, 2)
['05/04/2016 12:00:00' '19.05']
6118
(6118, 9)
Merging East Arjun Nagar-Delhi CPCB/Formaldehyde(For).csv
df2 shape(6109, 2)
['23/03/2017 00:00:00' '19.68']
6118
(6118, 10)
Saving East Arjun Nagar-Delhi CPCB/
Creating Sirifort/
Merging Sirifort/Wind Direction(WD).csv
df2 shape(4144, 2)
['01/02/2011 13:00:00' '320.0']
6547
(6547, 3)
Merging Sirifort/Solar Radiation(SR).csv
df2 shape(3177, 2)
['03/11/2016 13:00:00' '109.5']
6549
(6549, 4)
Merging Sirifort/Rain Fall(RAIN).csv
df2 shape(2389, 2)
['06/12/2016 09:00:00' '-1']
6549
(6549, 5)
Merging Sirifort/Ozone(OZONE).csv
df2 shape(3281, 2)
['01/02/2011 13:00:00' '28.25']
6549
(6549, 6)
Merging Sirifort/Suspended Particulate Matter.csv
Merging Sirifort/Ammonia(NH3).csv
df2 shape(3172, 2)
['03/11/2016 13:00:00' '11.65']
6549
(6549, 7)
Merging Sirifort/Non Methane Hydro Carbon(NMHC).csv
Merging Sirifort/M & P Xylene(M_P_Xylene).csv
Merging Sirifort/Oxides of Nitrogen(NOx).csv
df2 shape(5842, 2)
['01/02/2011 13:00:00' '11.0']
6549
(6549, 8)
Merging Sirifort/Nitrogen dioxide(NO2).csv
df2 shape(5841, 2)
['01/02/2011 13:00:00' '11.0']
6549
(6549, 9)
Merging Sirifort/Relative Humidity(RH).csv
df2 shape(3177, 2)
['03/11/2016 13:00:00' '29.3']
6549
(6549, 10)
Merging Sirifort/Carbon Monoxide(CO).csv
df2 shape(3281, 2)
['01/02/2011 13:00:00' '-1']
6549
(6549, 11)
Merging Sirifort/Toluene(Toluene).csv
Merging Sirifort/Sulfur Dioxide(SO2).csv
df2 shape(3281, 2)
['01/02/2011 13:00:00' '16.75']
6549
(6549, 12)
Merging Sirifort/PM10(RSPM).csv
Merging Sirifort/Temperature(Temp).csv
df2 shape(3173, 2)
['03/11/2016 17:00:00' '24.95']
6549
(6549, 13)
Merging Sirifort/PM2.5(PM2.5).csv
df2 shape(3039, 2)

KeyError: 'Date'

In [12]:
df.drop_duplicates()

,Time,Shadipur/O Xylene(O Xylene),Shadipur/Wind Speed (WS),Shadipur/Eth-Benzene(Eth-Benzene),Shadipur/Nitrogen Dioxide(NO2),Shadipur/Wind Direction(WD),Shadipur/Solar Radiation(SR),Shadipur/Relative Humidity(RH),Shadipur/Carbon Monoxide(CO),Shadipur/Toluene(Toluene),Shadipur/Sulfur Dioxide(SO2),Shadipur/Temperature(TEMP),Shadipur/Ozone(Ozone),Shadipur/NOx(NOx),Shadipur/Nitric Oxide(NO),Shadipur/Bar Pressure(BP),Shadipur/Benzene(Benzene),Shadipur/Vertical Wind Speed(VWS),Shadipur/MP Xylene(MP Xylene),Shadipur/PM 2.5(PM2.5)
0,01/01/2011 00:00:00,2.0,NaN,NaN,35.33,NaN,NaN,86.8,0.99,NaN,5.53,9.18,190.23,26.42,12.31,NaN,NaN,NaN,NaN,NaN
1,01/01/2011 01:00:00,1.3,NaN,NaN,35.56,NaN,NaN,86.29,0.56,NaN,5.55,9.81,121.03,30.00,16.96,NaN,NaN,NaN,NaN,NaN
2,03/01/2011 18:00:00,2.69,NaN,NaN,128.69,NaN,NaN,64.24,0.97,NaN,14.87,10.39,155.92,73.00,13.7,NaN,NaN,NaN,NaN,NaN
3,03/01/2011 19:00:00,6.0,NaN,NaN,101.21,NaN,NaN,71.98,1.41,NaN,12.12,9.1,129.63,57.62,11.05,NaN,NaN,NaN,NaN,NaN
4,03/01/2011 20:00:00,8.56,NaN,NaN,131.63,NaN,NaN,76.96,1.61,NaN,15.16,8.49,75.74,98.32,45.7,NaN,NaN,NaN,NaN,NaN
5,04/01/2011 03:00:00,0.25,NaN,NaN,53.61,NaN,NaN,85.94,0.54,NaN,7.36,6.05,120.48,68.15,56.28,NaN,NaN,NaN,NaN,NaN
6,04/01/2011 04:00:00,4.63,NaN,NaN,49.28,NaN,NaN,87.83,0.99,NaN,6.93,5.7,74.05,73.20,65.87,NaN,1.74,NaN,NaN,NaN
7,04/01/2011 05:00:00,6.28,NaN,NaN,52.72,NaN,NaN,87.98,0.85,NaN,7.27,5.58,72.88,90.55,86.88,NaN,24.98,NaN,NaN,NaN
8,04/01/2011 07:00:00,3.08,NaN,NaN,48.39,NaN,NaN,87.96,0.83,NaN,6.84,6.22,83.43,69.89,62.02,NaN,16.2,NaN,2.84,NaN
9,04/01/2011 09:00:00,0.13,NaN,NaN,52.52,NaN,NaN,75.25,0.59,NaN,7.25,7.54,41.16,44.83,25.75,NaN,NaN,NaN,NaN,NaN
10,04/01/2011 10:00:00,1.88,NaN,NaN,37.96,NaN,NaN,70.65,0.36,NaN,5.8,8.07,70.0,25.02,8.71,NaN,NaN,NaN,NaN,NaN
11,04/01/2011 20:00:00,1.24,NaN,NaN,38.09,NaN,NaN,73.45,0.85,NaN,5.8,6.64,63.73,24.34,7.72,NaN,NaN,NaN,NaN,NaN
12,06/01/2011 19:00:00,1.45,NaN,NaN,54.29,NaN,NaN,76.67,0.81,NaN,7.43,8.13,60.13,49.06,30.25,NaN,NaN,NaN,NaN,NaN
13,07/01/2011 12:00:00,0.81,NaN,NaN,119.61,NaN,NaN,52.28,1.14,NaN,13.96,11.69,66.75,65.59,9.7,NaN,NaN,NaN,NaN,NaN
14,07/01/2011 13:00:00,8.84,NaN,NaN,159.19,NaN,NaN,44.6,0.97,61.29,17.92,13.79,64.93,83.63,8.0,NaN,20.11,NaN,2.61,NaN
15,07/01/2011 14:00:00,13.37,NaN,NaN,155.13,NaN,NaN,46.14,0.59,82.19,17.51,14.04,55.81,79.78,5.5,NaN,30.44,NaN,3.50,NaN
16,07/01/2011 15:00:00,15.39,NaN,NaN,183.01,NaN,NaN,46.49,0.53,89.31,20.3,14.04,30.61,95.18,7.92,NaN,33.77,NaN,5.33,NaN
17,07/01/2011 21:00:00,3.74,NaN,NaN,130.0,NaN,NaN,78.13,0.78,NaN,3.48,8.63,8.69,127.18,85.44,NaN,NaN,NaN,NaN,NaN
18,07/01/2011 22:00:00,4.03,NaN,NaN,117.67,NaN,NaN,78.96,0.37,NaN,2.97,8.32,7.5,111.82,72.93,NaN,NaN,NaN,2.25,NaN
19,07/01/2011 23:00:00,2.38,NaN,NaN,94.34,NaN,NaN,80.66,0.05,NaN,NaN,7.82,7.34,64.81,25.18,NaN,NaN,NaN,NaN,NaN
20,08/01/2011 19:00:00,5.92,NaN,NaN,171.71,NaN,NaN,75.05,1.53,NaN,-1,8.71,12.93,155.77,96.5,NaN,NaN,NaN,5.83,NaN
21,08/01/2011 22:00:00,19.82,NaN,NaN,202.44,NaN,NaN,81.24,1.65,NaN,7.31,7.41,10.34,326.58,305.3,NaN,1.77,NaN,16.91,NaN
22,08/01/2011 23:00:00,19.64,NaN,NaN,107.15,NaN,NaN,86.14,0.29,NaN,NaN,6.6,5.89,115.55,84.8,NaN,2.27,NaN,12.68,NaN
23,09/01/2011 12:00:00,0.97,NaN,NaN,59.95,NaN,NaN,80.2,0.87,NaN,5.46,7.43,9.02,36.31,9.46,NaN,NaN,NaN,NaN,NaN
24,09/01/2011 15:00:00,1.79,NaN,NaN,57.4,NaN,NaN,71.64,0.07,NaN,3.94,9.21,16.35,33.99,8.03,NaN,NaN,NaN,NaN,NaN
25,09/01/2011 16:00:00,1.54,NaN,NaN,51.29,NaN,NaN,75.09,0.98,NaN,4.89,8.5,15.79,28.30,4.4,NaN,NaN,NaN,NaN,NaN
26,09/01/2011 17:00:00,3.83,NaN,NaN,52.67,NaN,NaN,77.74,1.14,NaN,5.05,8.16,12.33,28.60,3.9,NaN,NaN,NaN,NaN,NaN
27,09/01/2011 21:00:00,1.25,NaN,NaN,61.45,NaN,NaN,84.57,1.01,NaN,4.78,6.6,4.64,41.41,15.32,NaN,NaN,NaN,NaN,NaN
28,10/01/2011 18:00:00,2.03,NaN,NaN,99.52,NaN,NaN,64.96,0.85,NaN,5.13,10.76,27.73,53.93,7.21,NaN,NaN,NaN,NaN,NaN
29,10/01/2011 19:00:00,3.23,NaN,NaN,99.55,NaN,NaN,67.77,0.97,NaN,4.9,10.0,22.62,55.22,8.93,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297085,16/02/2016 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,40.22,0.7,-1,76.11,19.29,29.66,NaN,NaN,NaN,NaN,NaN,NaN,217.87
297086,16/02/2016 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,28.02,0.19,-1,86.67,21.24,64.76,NaN,NaN,NaN,NaN,NaN,NaN,184.51
297087,16/02/2016 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,20.75,0.1,NaN,44.16,22.63,94.96,NaN,NaN,NaN,NaN,NaN,NaN,231.18
297088,16/02/2016 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,15.45,0.22,-1,31.62,23.5,102.92,NaN,NaN,NaN,NaN,NaN,NaN,228.36
297089,16/02/2016 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,13.89,0.1,NaN,21.39,23.85,126.36,NaN,NaN,NaN,NaN,NaN,NaN,184.77
297090,16/02/2016 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,12.16,0.14,-1,16.48,25.43,51.93,NaN,NaN,NaN,NaN,NaN,NaN,239.08
297091,16/02/2016 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.53,NaN,NaN,NaN,19.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297092,17/02/2016 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297093,17/02/2016 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297094,17/02/2016 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297095,17/02/2016 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297096,17/02/2016 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297097,17/02/2016 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297098,17/02/2016 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297099,17/02/2016 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297100,17/02/2016 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,39.74,NaN,NaN,NaN,19.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297101,19/02/2016 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,70.42,0.17,NaN,24.27,22.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.98
297102,19/02/2016 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,54.15,1.29,NaN,48.09,24.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.66
297103,19/02/2016 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,41.89,1.75,NaN,42.62,26.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166.28
297104,19/02/2016 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,35.31,0.51,NaN,38.43,27.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159.27
297105,19/02/2016 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,33.94,0.22,NaN,33.08,28.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.79
297106,19/02/2016 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,26.56,0.46,NaN,31.66,29.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171.82
297107,19/02/2016 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,31.16,0.65,NaN,19.73,28.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161.16
297108,19/02/2016 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,41.37,1.05,NaN,23.92,27.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169.16
297109,19/02/2016 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,49.32,1.49,NaN,23.11,26.26,10.35,NaN,NaN,NaN,NaN,NaN,NaN,185.04
297110,25/02/2016 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,15.49,0.79,NaN,2.46,28.39,143.7,NaN,NaN,NaN,NaN,NaN,NaN,198.75
297111,29/02/2016 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,47.55,3.47,NaN,85.52,26.34,48.64,NaN,NaN,NaN,NaN,NaN,NaN,232.38
297112,16/02/2016 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.19,-1,17.12,NaN,127.4,NaN,NaN,NaN,NaN,NaN,NaN,224.53
297113,21/06/2011 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297114,24/01/2017 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.45,28.68,NaN,NaN,NaN,NaN,NaN,NaN